const CHUNK_PUBLIC_PATH = "server/app/page.js";
const runtime = require("../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/65a4b_next_dist_5ef57d._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__adba9d._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__6afcf5._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__340542._.css");
runtime.loadChunk("server/chunks/ssr/node_modules__pnpm_67c9d9._.js");
runtime.loadChunk("server/chunks/ssr/node_modules__pnpm_52d98f._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__352b26._.js");
runtime.loadChunk("server/chunks/ssr/app_ui_home_module_6dd21e.css");
runtime.getOrInstantiateRuntimeModule("[project]/.next-internal/server/app/page/actions.js [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/.pnpm/next@15.0.0_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__react@19.0.0-rc-cd22717c-20241013/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { MODULE_0 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_1 => \"[project]/node_modules/.pnpm/next@15.0.0_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__react@19.0.0-rc-cd22717c-20241013/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_2 => \"[project]/app/page.tsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH).exports;
